function h(){$(".navbar-toggle").click(function(a){var b=$(this).closest("nav"),c=b.find("ul.site-navigation"),d=c.clone();c.parent().j("nav-special")&&((a.stopPropagation(),$(this).j("selected-nav"))?($(".blocsapp-special-menu blocsnav").i("open"),$(".selected-nav").i("selected-nav"),setTimeout(function(){$(".blocsapp-special-menu").remove();$("body").i("lock-scroll");$(".selected-nav").i("selected-nav")},300)):($(this).h("selected-nav"),a=b.g("class").replace("navbar","").replace("row",""),c=c.parent().g("class").replace("navbar-collapse",
"").replace("collapse",""),$(".content-tint").length=-1,$("body").append('<div class="content-tint"></div>'),d.insertBefore(".page-container").P('<div class="blocsapp-special-menu '+a+'"><blocsnav class="'+c+'">'),$("blocsnav").prepend('<a class="close-special-menu animated fadeIn" style="animation-delay:0.5s;"><div class="close-icon"></div></a>'),function(){var e="fadeInRight",f=0,g=60;$(".blocsapp-special-menu blocsnav").j("fullscreen-nav")?(e="fadeIn",g=100):$(".blocsapp-special-menu").j("nav-invert")&&
(e="fadeInLeft");$(".blocsapp-special-menu blocsnav li").o(function(){$(this).parent().j("dropdown-menu")?$(this).h("animated fadeIn"):(f+=g,$(this).g("style","animation-delay:"+f+"ms").h("animated "+e))})}(),setTimeout(function(){$(".blocsapp-special-menu blocsnav").h("open");$(".content-tint").h("on");$("body").h("lock-scroll")},10)))});$("body").s("mousedown touchstart",".content-tint, .close-special-menu",function(){$(".content-tint").i("on");$(".selected-nav").click();setTimeout(function(){$(".content-tint").remove()},
10)}).s("click",".blocsapp-special-menu a",function(a){$(a.target).closest(".dropdown-toggle").length||$(".close-special-menu").J()})}
function k(){$(".site-navigation a").click(function(a){$(a.target).closest(".dropdown-toggle").length||$(".navbar-collapse").collapse("hide")});$("a.dropdown-toggle").click(function(){$(this).parent().h("target-open-menu");$(this).closest(".dropdown-menu").find(".dropdown.open").o(function(){$(this).j("target-open-menu")||$(this).i("open")});$(".target-open-menu").i("target-open-menu")})}
function l(){$(".bloc-fill-screen").o(function(){var a=$(this);window.G=0;$(this).find(".container").o(function(){fillPadding=2*parseInt($(this).m("padding-top"));a.j("bloc-group")?fillBodyHeight=fillPadding+$(this).outerHeight()+50:fillBodyHeight=fillBodyHeight+fillPadding+$(this).outerHeight()+50});$(this).m("height",m()+"px")})}function m(){var a=$(window).height();return a<fillBodyHeight&&(a=fillBodyHeight+100),a}
function n(){p();q();$(window).scroll(function(){q();$(window).scrollTop()>$(window).height()/3?$(".scrollToTop").j("showScrollTop")||$(".scrollToTop").h("showScrollTop"):$(".scrollToTop").i("showScrollTop");var a=0,b="sticky";$(".sticky-nav").j("fill-bloc-top-edge")&&(a=$(".fill-bloc-top-edge.sticky-nav").parent().m("background-color"),"rgba(0, 0, 0, 0)"==a&&(a="#FFFFFF"),$(".sticky-nav").m("background",a),a=$(".sticky-nav").height(),b="sticky animated fadeInDown");$(window).scrollTop()>a?($(".sticky-nav").h(b),
"sticky"==b&&$(".page-container").m("padding-top",$(".sticky-nav").height())):($(".sticky-nav").i(b).v("style"),$(".page-container").v("style"))})}function r(){$("ul.dropdown-menu [data-toggle=dropdown]").s("click",function(a){a.preventDefault();a.stopPropagation();$(this).parent().K().i("open");$(this).parent().N("open");a=$(this).parent().children(".dropdown-menu");a.offset().left+a.width()>$(window).width()&&a.h("dropmenu-flow-right")})}
function p(){$(".animated").o(function(){$(this).closest(".hero").length||$(this).i("animated").h("hideMe")})}function q(){$($(".hideMe").get().reverse()).o(function(){var a=jQuery(this),b=a.offset().top+a.height(),c=$(window).scrollTop()+$(window).height();if(a.height()>$(window).height()&&(b=a.offset().top),b<c){var d=a.g("class").replace("hideMe","animated");a.m("visibility","hidden").v("class");setTimeout(function(){a.g("class",d).m("visibility","visible")},.01)}})}
function t(){$(document).s("click","[data-toggle-visibility]",function(a){function b(d){d.is("img")?d.toggle():d.L()}a.preventDefault();a=$(this).g("data-toggle-visibility");if(-1!=a.indexOf(",")){var c=a.split(",");$.o(c,function(d){b($("#"+c[d]))})}else b($("#"+a))})}
function u(){window.M;$(document).s("click","[data-lightbox]",function(a){a.preventDefault();targetLightbox=$(this);a=targetLightbox.g("data-lightbox");var b=targetLightbox.g("data-autoplay"),c='<p class="lightbox-caption">'+targetLightbox.g("data-caption")+"</p>",d="no-gallery-set",e=targetLightbox.g("data-frame");targetLightbox.g("data-gallery-id")&&(d=targetLightbox.g("data-gallery-id"));targetLightbox.g("data-caption")||(c="");var f="";1==b&&(f="autoplay");b=$('<div id="lightbox-modal" class="modal fade"><div class="modal-dialog"><div class="modal-content '+
e+' blocs-lb-container"><button id="blocs-lightbox-close-btn" type="button" class="close-lightbox" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button><div class="modal-body"><a href="#" class="prev-lightbox" aria-label="prev"><span class="fa fa-chevron-left"></span></a><a href="#" class="next-lightbox" aria-label="next"><span class="fa fa-chevron-right"></span></a><img id="lightbox-image" class="img-responsive" src="'+a+'"><div id="lightbox-video-container" class="embed-responsive embed-responsive-16by9"><video controls '+
f+' class="embed-responsive-item"><source id="lightbox-video" src="'+a+'" type="video/mp4"></video></div>'+c+"</div></div></div></div>");$("body").append(b);"fullscreen-lb"==e&&($("#lightbox-modal").h("fullscreen-modal").append('<a class="close-full-screen-modal animated fadeIn" style="animation-delay:0.5s;" onclick="$(\'#lightbox-modal\').modal(\'hide\');"><div class="close-icon"></div></a>'),$("#blocs-lightbox-close-btn").remove());".mp4"==a.substring(a.length-4)?($("#lightbox-image, .lightbox-caption").l(),
$("#lightbox-video-container").show()):($("#lightbox-image,.lightbox-caption").show(),$("#lightbox-video-container").l());$("#lightbox-modal").I("show");"no-gallery-set"==d?(0==$("a[data-lightbox]").index(targetLightbox)&&$(".prev-lightbox").l(),$("a[data-lightbox]").index(targetLightbox)==$("a[data-lightbox]").length-1&&$(".next-lightbox").l()):(0==$('a[data-gallery-id="'+d+'"]').index(targetLightbox)&&$(".prev-lightbox").l(),$('a[data-gallery-id="'+d+'"]').index(targetLightbox)==$('a[data-gallery-id="'+
d+'"]').length-1&&$(".next-lightbox").l());v()}).s("hidden.bs.modal","#lightbox-modal",function(){$("#lightbox-modal").remove()});$(document).s("click",".next-lightbox, .prev-lightbox",function(a){a.preventDefault();a="no-gallery-set";var b=$("a[data-lightbox]").index(targetLightbox),c=$("a[data-lightbox]").u(b+1);targetLightbox.g("data-gallery-id")&&(a=targetLightbox.g("data-gallery-id"),b=$('a[data-gallery-id="'+a+'"]').index(targetLightbox),c=$('a[data-gallery-id="'+a+'"]').u(b+1));$(this).j("prev-lightbox")&&
(c=$('a[data-gallery-id="'+a+'"]').u(b-1),"no-gallery-set"==a&&(c=$("a[data-lightbox]").u(b-1)));b=c.g("data-lightbox");if(".mp4"==b.substring(b.length-4)){var d="";1==c.g("data-autoplay")&&(d="autoplay");$("#lightbox-image, .lightbox-caption").l();$("#lightbox-video-container").show().B("<video controls "+d+' class="embed-responsive-item"><source id="lightbox-video" src="'+b+'" type="video/mp4"></video>')}else $("#lightbox-image").g("src",b).show(),$(".lightbox-caption").B(c.g("data-caption")).show(),
$("#lightbox-video-container").l();targetLightbox=c;$(".next-lightbox, .prev-lightbox").l();"no-gallery-set"==a?($("a[data-lightbox]").index(c)!=$("a[data-lightbox]").length-1&&$(".next-lightbox").show(),0<$("a[data-lightbox]").index(c)&&$(".prev-lightbox").show()):($('a[data-gallery-id="'+a+'"]').index(c)!=$('a[data-gallery-id="'+a+'"]').length-1&&$(".next-lightbox").show(),0<$('a[data-gallery-id="'+a+'"]').index(c)&&$(".prev-lightbox").show())})}
function w(){$(".carousel-inner").length&&$(".carousel-inner").C({D:function(){$(this).parent().A("next")},F:function(){$(this).parent().A("prev")},threshold:0})}function x(){$(window).H(function(a){37==a.which?$(".prev-lightbox").is(":visible")&&$(".prev-lightbox").click():39==a.which&&$(".next-lightbox").is(":visible")&&$(".next-lightbox").click()})}
function v(){$("#lightbox-image").length&&$("#lightbox-image").C({D:function(){$(".next-lightbox").is(":visible")&&$(".next-lightbox").click()},F:function(){$(".prev-lightbox").is(":visible")&&$(".prev-lightbox").click()},threshold:0})}
$(document).ready(function(){$("#scroll-hero").click(function(a){a.preventDefault();$("html,body").animate({scrollTop:$("#scroll-hero").closest(".bloc").height()},"slow")});k();h();r();u();t();w();x();-1!=navigator.userAgent.indexOf("Safari")&&-1==navigator.userAgent.indexOf("Chrome")&&$("#page-loading-blocs-notifaction").remove()});$(window).load(function(){l();n();$("#page-loading-blocs-notifaction").remove()}).resize(function(){l()});$(function(){$('[data-toggle="tooltip"]').O()});